- type: job
  id: Captain
  name: job-name-captain
  description: job-description-captain
  playTimeTracker: JobCaptain
  weight: 20
  startingGear: CaptainGear
  icon: "JobIconCaptain"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: CaptainGear
  equipment:

#    jumpsuit: ClothingShirtTShirtCommand
#    lowerClothing: ClothingPantsJeans
#    mask: ClothingMaskBandBlue
#    eyes: ClothingEyesGlassesSunglasses
#    ears: ClothingHeadsetAltCommand
#    outerClothing: ClothingOuterCoatTrenchDark
#    pocket2: BasicPager

    belt: Machete
    pocket1: WeaponRevolverDeckard
    eyes: ClothingEyesGlassesSunglasses
    id: CaptainPDA
    ears: ClothingHeadsetAltCommand
  storage:
    back:
    - BoxSurvival
    - Flash
    # - StationCharter
