using Content.Client.Computer;
using Content.Client.UserInterface.Controls;
using Content.Shared._Ekrixi.ShipWeapons;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;

namespace Content.Client._Ekrixi.ShipWeapons;

[GenerateTypedNameReferences]
public sealed partial class GunnerComputerWindow : FancyWindow,
    IComputerWindow<GunnerComputerBoundUserInterface>
{
    public event Action<EntityCoordinates>? OnRadarClick;
    public event Action? OnFireClick;
    public event Action? OnEjectClick;
    public event Action<bool>? OnAutofireClick;
    public event Action? OnChamberClick;

    public GunnerComputerWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        WorldRangeChange(RadarScreen.WorldRange);
        RadarScreen.WorldRangeChanged += WorldRangeChange;
        RadarScreen.OnRadarClick += coordinates =>
        {
            OnRadarClick?.Invoke(coordinates);
        };

        FireButton.OnButtonDown += _ => { OnFireClick?.Invoke(); };
        EjectButton.OnButtonDown += _ => { OnEjectClick?.Invoke(); };
        ChamberButton.OnButtonDown += _ => { OnChamberClick?.Invoke(); };
        AutofireButton.OnButtonDown += AutofireButtonPressed;
    }

    private void AutofireButtonPressed(BaseButton.ButtonEventArgs args)
    {
        OnAutofireClick?.Invoke(args.Button.Pressed);
    }

    private void WorldRangeChange(float value)
    {
        RadarRange.Text = $"{value:0}m";
    }

    public void SetMatrix(EntityCoordinates? coordinates, Angle? angle)
    {
        RadarScreen.SetMatrix(coordinates, angle);
    }

    public void UpdateState(GunnerComputerBoundInterfaceState scc)
    {
        // update the radar
        RadarScreen.UpdateState(scc.State);

        // update ammo text
        var currentAmmo = 0;
        var ammoCapacity = 0;

        bool? autofiring = null;
        var desynced = false;
        var hasTurrets = scc.Turrets.Count > 0;

        foreach (var turret in scc.Turrets)
        {
            currentAmmo += turret.CurrentAmmo;
            ammoCapacity += turret.AmmoCapacity;

            if (desynced)
                continue;
            if (!autofiring.HasValue)
                autofiring = turret.Autofire;
            else
            {
                if (autofiring.Value != turret.Autofire)
                    desynced = true;
            }
        }

        AutofireButton.Pressed = autofiring ?? false;
        var text = "broken; call rain";

        if (!hasTurrets || !autofiring.HasValue)
        {
            text = "No data";
        }
        else if (desynced)
        {
            text = "Desynced";
        }
        else
        {
            text = autofiring.Value ? "Enabled" : "Disabled";
        }

        AutofireLabel.Text = text;

        AmmoCounter.Text = currentAmmo <= 0 ? Loc.GetString("gunner-computer-no-ammo-text") : $"{currentAmmo}/{ammoCapacity}";
        MaxRadarRange.Text = $"{scc.State.MaxRange:0}m";
    }
}
