- type: entity
  parent: BaseStructure
  id: EkrixiBaseShipWeapon
  name: ship weapon
  abstract: true
  components:
  - type: Clickable
  - type: InteractionOutline
  - type: Actions
  - type: Rotatable
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-0.45,-0.45,0.45,0.45"
        density: 60
        mask:
        - MachineMask
        layer:
        - MachineLayer
  - type: ContainerContainer
    containers:
      ballistic-ammo: !type:Container
  - type: Sprite
    sprite: _Ekrixi/Structures/Weapons/ShipWeapons/autocannon_120mm.rsi
    drawdepth: Mobs
    layers:
    - state: autocannon_120mm
  - type: Damageable
    damageContainer: Inorganic
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 600
      behaviors:
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
    - trigger:
        !type:DamageTrigger
        damage: 300
      # TODO: Construction graph
      behaviors:
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
      - !type:PlaySoundBehavior
        sound:
          collection: MetalGlassBreak
      - !type:SpawnEntitiesBehavior
        spawn:
          SheetSteel1:
            min: 3
            max: 5
  - type: NoRotateOnInteract
  - type: NoRotateOnMove
  - type: DeviceNetwork
    deviceNetId: Wireless
    receiveFrequencyId: BasicDevice
  - type: DeviceLinkSink
    ports:
    - EkrixiFire
    - EkrixiAim
    - EkrixiAutofire
  - type: DeviceLinkSource
    ports:
    - EkrixiDataGunnery
  - type: ShipWeapon # Define this as a ship weapon
  - type: Gun # Make the gun actually owrk
    fireRate: 6
    selectedMode: FullAuto
    availableModes:
    - FullAuto
    soundGunshot: /Audio/Weapons/Guns/Gunshots/gun_sentry.ogg
  - type: ChamberMagazineAmmoProvider
    soundRack:
      path: /Audio/Weapons/Guns/Cock/smg_cock.ogg
  - type: ItemSlots
    slots:
      gun_magazine:
        name: Magazine
        startingItem: MagazineCaselessRifle
        insertSound: /Audio/Weapons/Guns/MagIn/smg_magin.ogg
        ejectSound: /Audio/Weapons/Guns/MagOut/smg_magout.ogg
        priority: 2
        whitelist:
          tags:
          - MagazineRifle
          - MagazineCaselessRifle
        whitelistFailPopup: gun-magazine-whitelist-fail
      gun_chamber:
        name: Chamber
        startingItem: CartridgeCaselessRifle
        priority: 1
        whitelist:
          tags:
          - CartridgeRifle
          - CartridgeCaselessRifle

- type: entity
  parent: EkrixiBaseShipWeapon
  id: EkrixiShipWeapon
  name: gun
  suffix: Ekrixi
  components:
  - type: ShipWeapon
    rotationSpeed: 7.85
  - type: Gun
    fireRate: 8
